name: "test-device-profile"
manufacturer: "testing"
model: "testing"
labels:
- "modbus"
- "scalability test"
description: "Mock Modbus device for scalability test."

deviceResources:
-
  name: "int16-1"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "1" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-2"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "2" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-3"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "3" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-4"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "4" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-5"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "5" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-6"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "6" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-7"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "7" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-8"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "8" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-9"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "9" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-10"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: "10" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
    
-
  name: "int16-11"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "11" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-12"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "12" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-13"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "13" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-14"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "14" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-15"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "15" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-16"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "16" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-17"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "17" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-18"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "18" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-19"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "19" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "int16-20"
  description: "test int value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: "20" }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    defaultValue: "0"
    
    
-
  name: "bool-1"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "1" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"

-
  name: "bool-2"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "2" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"

-
  name: "bool-3"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "3" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-4"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "4" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-5"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "5" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-6"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "6" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-7"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "7" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-8"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "8" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-9"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "9" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-10"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: "10" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"


-
  name: "bool-11"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "11" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-12"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "12" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-13"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "13" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-14"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "14" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"

-
  name: "bool-15"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "15" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-16"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "16" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-17"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "17" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-18"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "18" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-19"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "19" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "bool-20"
  description: "test bool value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: "20" }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: "1"
    minimum: "0"
    maximum: "1"
    defaultValue: "0"

deviceCommands:
-
  name: "integerA"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "int16-1"
    - deviceResource: "int16-2"
    - deviceResource: "int16-3"
    - deviceResource: "int16-4"
    - deviceResource: "int16-5"
    - deviceResource: "int16-6"
    - deviceResource: "int16-7"
    - deviceResource: "int16-8"
    - deviceResource: "int16-9"
    - deviceResource: "int16-10"
-
  name: "integerB"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "int16-11"
    - deviceResource: "int16-12"
    - deviceResource: "int16-13"
    - deviceResource: "int16-14"
    - deviceResource: "int16-15"
    - deviceResource: "int16-16"
    - deviceResource: "int16-17"
    - deviceResource: "int16-18"
    - deviceResource: "int16-19"
    - deviceResource: "int16-20"

-
  name: "booleanA"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "bool-1"
    - deviceResource: "bool-2"
    - deviceResource: "bool-3"
    - deviceResource: "bool-4"
    - deviceResource: "bool-5"
    - deviceResource: "bool-6"
    - deviceResource: "bool-7"
    - deviceResource: "bool-8"
    - deviceResource: "bool-9"
    - deviceResource: "bool-10"
-
  name: "booleanB"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "bool-11"
    - deviceResource: "bool-12"
    - deviceResource: "bool-13"
    - deviceResource: "bool-14"
    - deviceResource: "bool-15"
    - deviceResource: "bool-16"
    - deviceResource: "bool-17"
    - deviceResource: "bool-18"
    - deviceResource: "bool-19"
    - deviceResource: "bool-20"
