name: "Virtual-Sample-Profile"
manufacturer: "Company"
model: "Device-01"
labels:
- "device-virtual"
description: "Example of device-virtual"

deviceResources:
-  ### Binary ###  # not support write
  name: "Virtual_DeviceValue_Binary_R"
  description: "Generate device binary value"
  properties:
    valueType: "Binary"
    readWrite: "R"
    mediaType: "random"
-  ### Boolean ###
  name: "Virtual_DeviceValue_Boolean_RW"
  description: "Generate device boolean value"
  isHidden: true
  tag: "status"
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    minimum: "0"
    maximum: "1"
    defaultValue: "true"
-
  name: "Virtual_DeviceValue_Boolean_R"
  description: "Generate device boolean value"
  properties:
    valueType: "BOOL"
    readWrite: "R"
    minimum: "0"
    maximum: "1"
    defaultValue: "true"
-
  name: "Virtual_DeviceValue_Boolean_W"
  description: "Generate device boolean value"
  properties:
    valueType: "BOOL"
    readWrite: "W"
    minimum: "0"
    maximum: "1"
    defaultValue: "true"
-  ### FLOAT32 ###
  name: "Virtual_DeviceValue_FLOAT32_RW"
  description: "Generate device FLOAT32 value"
  properties:
    valueType: "Float32"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_FLOAT32_R"
  description: "Generate device FLOAT32 value"
  properties:
    valueType: "Float32"
    readWrite: "R"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_FLOAT32_W"
  description: "Generate device FLOAT32 value"
  properties:
    valueType: "Float32"
    readWrite: "W"
    defaultValue: "0"
-  ### FLOAT64 ###
  name: "Virtual_DeviceValue_FLOAT64_RW"
  description: "Generate device FLOAT64 value"
  properties:
    valueType: "Float64"
    readWrite: "RW"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_FLOAT64_R"
  description: "Generate device FLOAT64 value"
  properties:
    valueType: "Float64"
    readWrite: "R"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_FLOAT64_W"
  description: "Generate device FLOAT64 value"
  properties:
    valueType: "Float64"
    readWrite: "W"
    defaultValue: "0"
-  ### INT8 ###
  name: "Virtual_DeviceValue_INT8_RW"
  description: "Generate device INT8 value"
  properties:
    valueType: "Int8"
    readWrite: "RW"
    minimum: "-128"
    maximum: "127"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT8_R"
  description: "Generate device INT8 value"
  properties:
    valueType: "Int8"
    readWrite: "R"
    minimum: "-128"
    maximum: "127"
    defaultValue: "0"
    units: "ms"
-
  name: "Virtual_DeviceValue_INT8_W"
  description: "Generate device INT8 value"
  properties:
    valueType: "Int8"
    readWrite: "W"
    minimum: "-128"
    maximum: "127"
    defaultValue: "0"
-  ### INT16 ###
  name: "Virtual_DeviceValue_INT16_RW"
  description: "Generate device INT16 value"
  properties:
    valueType: "Int16"
    readWrite: "RW"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT16_R"
  description: "Generate device INT16 value"
  properties:
    valueType: "Int16"
    readWrite: "R"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT16_W"
  description: "Generate device INT16 value"
  properties:
    valueType: "Int16"
    readWrite: "W"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "0"
-  ### INT32 ###
  name: "Virtual_DeviceValue_INT32_RW"
  description: "Generate device INT32 value"
  properties:
    valueType: "Int32"
    readWrite: "RW"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT32_R"
  description: "Generate device INT32 value"
  properties:
    valueType: "Int32"
    readWrite: "R"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT32_W"
  description: "Generate device INT32 value"
  properties:
    valueType: "Int32"
    readWrite: "W"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "0"
-  ### INT64 ###
  name: "Virtual_DeviceValue_INT64_RW"
  description: "Generate device INT64 value"
  properties:
    valueType: "Int64"
    readWrite: "RW"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT64_R"
  description: "Generate device INT64 value"
  properties:
    valueType: "Int64"
    readWrite: "R"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_INT64_W"
  description: "Generate device INT64 value"
  properties:
    valueType: "Int64"
    readWrite: "W"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "0"
-  ### UINT8 ###
  name: "Virtual_DeviceValue_UINT8_RW"
  description: "Generate device UINT8 value"
  properties:
    valueType: "Uint8"
    readWrite: "RW"
    minimum: "0"
    maximum: "255"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT8_R"
  description: "Generate device UINT8 value"
  properties:
    valueType: "Uint8"
    readWrite: "R"
    minimum: "0"
    maximum: "255"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT8_W"
  description: "Generate device UINT8 value"
  properties:
    valueType: "Uint8"
    readWrite: "W"
    minimum: "0"
    maximum: "255"
    defaultValue: "0"
-  ### UINT16 ###
  name: "Virtual_DeviceValue_UINT16_RW"
  description: "Generate device UINT16 value"
  properties:
    valueType: "Uint16"
    readWrite: "RW"
    minimum: "0"
    maximum: "65535"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT16_R"
  description: "Generate device UINT16 value"
  properties:
    valueType: "Uint16"
    readWrite: "R"
    minimum: "0"
    maximum: "65535"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT16_W"
  description: "Generate device UINT16 value"
  properties:
    valueType: "Uint16"
    readWrite: "W"
    minimum: "0"
    maximum: "65535"
    defaultValue: "0"
-  ### UINT32 ###
  name: "Virtual_DeviceValue_UINT32_RW"
  description: "Generate device UINT32 value"
  properties:
    valueType: "Uint32"
    readWrite: "RW"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "0"
    shift: "-16"
-
  name: "Virtual_DeviceValue_UINT32_R"
  description: "Generate device UINT32 value"
  properties:
    valueType: "Uint32"
    readWrite: "R"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT32_W"
  description: "Generate device UINT32 value"
  properties:
    valueType: "Uint32"
    readWrite: "W"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "0"
-  ### UINT64 ###
  name: "Virtual_DeviceValue_UINT64_RW"
  description: "Generate device UINT64 value"
  properties:
    valueType: "Uint64"
    readWrite: "RW"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT64_R"
  description: "Generate device UINT64 value"
  properties:
    valueType: "Uint64"
    readWrite: "R"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "0"
-
  name: "Virtual_DeviceValue_UINT64_W"
  description: "Generate device UINT64 value"
  properties:
    valueType: "Uint64"
    readWrite: "W"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "0"

deviceCommands:
-  ### Binary ###
  name: "Virtual_GenerateDeviceValue_Binary_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_Binary_R"
-  ### Boolean ###
  name: "Virtual_GenerateDeviceValue_Boolean_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_Boolean_RW"
- name: "Virtual_GenerateDeviceValue_Boolean_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_Boolean_R"
- name: "Virtual_GenerateDeviceValue_Boolean_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_Boolean_W"
-  ### FLOAT32 ###
  name: "Virtual_GenerateDeviceValue_FLOAT32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT32_RW"
-
  name: "Virtual_GenerateDeviceValue_FLOAT32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT32_R"
-
  name: "Virtual_GenerateDeviceValue_FLOAT32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT32_W"
-  ### FLOAT64 ###
  name: "Virtual_GenerateDeviceValue_FLOAT64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT64_RW"
-
  name: "Virtual_GenerateDeviceValue_FLOAT64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT64_R"
-
  name: "Virtual_GenerateDeviceValue_FLOAT64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_FLOAT64_W"
-  ### INT8 ###
  name: "Virtual_GenerateDeviceValue_INT8_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT8_RW"
-
  name: "Virtual_GenerateDeviceValue_INT8_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT8_R"
-
  name: "Virtual_GenerateDeviceValue_INT8_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT8_W"
-  ### INT16 ###
  name: "Virtual_GenerateDeviceValue_INT16_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT16_RW"
-
  name: "Virtual_GenerateDeviceValue_INT16_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT16_R"
-
  name: "Virtual_GenerateDeviceValue_INT16_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT16_W"
-  ### INT32 ###
  name: "Virtual_GenerateDeviceValue_INT32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT32_RW"
-
  name: "Virtual_GenerateDeviceValue_INT32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT32_R"
-
  name: "Virtual_GenerateDeviceValue_INT32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT32_W"
-  ### INT64 ###
  name: "Virtual_GenerateDeviceValue_INT64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT64_RW"
-
  name: "Virtual_GenerateDeviceValue_INT64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT64_R"
-
  name: "Virtual_GenerateDeviceValue_INT64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_INT64_W"
-  ### UINT8 ###
  name: "Virtual_GenerateDeviceValue_UINT8_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT8_RW"
-
  name: "Virtual_GenerateDeviceValue_UINT8_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT8_R"
-
  name: "Virtual_GenerateDeviceValue_UINT8_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT8_W"
-  ### UINT16 ###
  name: "Virtual_GenerateDeviceValue_UINT16_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT16_RW"
-
  name: "Virtual_GenerateDeviceValue_UINT16_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT16_R"
-
  name: "Virtual_GenerateDeviceValue_UINT16_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT16_W"
-  ### UINT32 ###
  name: "Virtual_GenerateDeviceValue_UINT32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT32_RW"
-
  name: "Virtual_GenerateDeviceValue_UINT32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT32_R"
-
  name: "Virtual_GenerateDeviceValue_UINT32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT32_W"
-  ### UINT64 ###
  name: "Virtual_GenerateDeviceValue_UINT64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT64_RW"
-
  name: "Virtual_GenerateDeviceValue_UINT64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT64_R"
-
  name: "Virtual_GenerateDeviceValue_UINT64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Virtual_DeviceValue_UINT64_W"
