  
  device-virtual:
    image: ${virtual}
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:rw,z
    depends_on:
    - data
    - command
    entrypoint:
      - /device-virtual
      - --profile=${DS_PROFILE}
      - --registry=${REGISTRY_URL}
      - --confdir=${CONF_DIR}

  device-random:
    image: ${random}
    ports:
     - "49988:49988"
    container_name: edgex-device-random
    hostname: edgex-device-random
    networks:
     edgex-network:
       aliases:
           - edgex-device-random
    volumes:
     - db-data:/data/db
     - log-data:/edgex/logs
     - consul-config:/consul/config
     - consul-data:/consul/data
     - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:rw,z
    depends_on:
     - data
     - command
    entrypoint:
      - /device-random
      - --profile=${DS_PROFILE}
      - --registry=${REGISTRY_URL}
      - --confdir=${CONF_DIR}

  # device-mqtt:
  #   image: ${mqtt}
  #   ports:
  #     - "49982:49982"
  #   container_name: edgex-device-mqtt
  #   hostname: edgex-device-mqtt
  #   networks:
  #     edgex-network:
  #       aliases:
  #           - edgex-device-mqtt
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  edgex-device-modbus:
    image: ${modbus}
    ports:
      - "49991:49991"
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    networks:
      edgex-network:
        aliases:
          - edgex-device-modbus
    volumes:
     - db-data:/data/db
     - log-data:/edgex/logs
     - consul-config:/consul/config
     - consul-data:/consul/data
     - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:rw,z
    depends_on:
     - data
     - command
     - modbus-simulator
    entrypoint:
      - /device-modbus
      - --profile=${DS_PROFILE}
      - --registry=${REGISTRY_URL}
      - --confdir=${CONF_DIR}

  modbus-simulator:
    image: ${modbusSimulator}
    ports:
     - "502:502"

