  device-virtual:
    image: ${virtual}
    ports:
    - 127.0.0.1:49990:49990/tcp
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    environment:
      REGISTRY_HOST: edgex-core-consul
      CLIENTS_DATA_HOST: edgex-core-data
      CLIENTS_METADATA_HOST: edgex-core-metadata
      SERVICE_HOST: edgex-device-virtual
    entrypoint: ["/device-virtual"]
    command: ["--registry","--confdir=${CONF_DIR}"]
    volumes:
      - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:z
    depends_on:
      - consul
      - data
      - command

  edgex-device-modbus:
    image: ${modbus}
    ports:
      - 127.0.0.1:49991:49991/tcp
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    networks:
      - edgex-network
    environment:
      REGISTRY_HOST: edgex-core-consul
      CLIENTS_DATA_HOST: edgex-core-data
      CLIENTS_METADATA_HOST: edgex-core-metadata
      SERVICE_HOST: edgex-device-modbus
    entrypoint: ["/device-modbus"]
    command: ["--registry","--confdir=${CONF_DIR}"]
    volumes:
      - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:z
    depends_on:
      - consul
      - data
      - command
      - modbus-simulator

  modbus-simulator:
    image: ${modbusSimulator}
    container_name: edgex-modbus-simulator
    hostname: edgex-modbus-simulator
    ports:
      - 127.0.0.1:1502:1502/tcp
    networks:
      - edgex-network
