  device-virtual:
    image: ${virtual}
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    environment:
      <<: *common-variables
      Service_Host: edgex-device-virtual
    entrypoint: ["/device-virtual"]
    command: ["--registry","--confdir=${CONF_DIR}", "--profile=${DS_PROFILE}"]
    volumes:
      - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:rw,z
    depends_on:
      - consul
      - data
      - command

  edgex-device-modbus:
    image: ${modbus}
    ports:
      - "49991:49991"
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    entrypoint: ["/device-modbus"]
    command: ["--registry","--confdir=${CONF_DIR}", "--profile=${DS_PROFILE}"]
    networks:
      edgex-network:
        aliases:
          - edgex-device-modbus
    environment:
      <<: *common-variables
      Service_Host: edgex-device-modbus
    volumes:
      - ${WORK_DIR}/TAF/config/${PROFILE}:${CONF_DIR}:rw,z
    depends_on:
      - consul
      - data
      - command
      - modbus-simulator

  modbus-simulator:
    image: ${modbusSimulator}
    container_name: edgex-modbus-simulator
    hostname: edgex-modbus-simulator
    ports:
      - "1502:1502"
    networks:
      - edgex-network

