  app-service-http-export:
    image: ${appService}
    ports:
      - "48096:48096"
    container_name: app-service-http-export
    hostname: app-service-http-export
    environment:
      edgex_profile: http-export
      Service_Host: app-service-http-export
      Clients_CoreData_Host: edgex-core-data
      Clients_Logging_Host: edgex-support-logging
      Registry_Host: edgex-core-consul
      Service_Port: 48096
      MessageBus_SubscribeHost_Host: edgex-core-data
      Database_Host: edgex-mongo
      Database_Username: appservice
      Database_Password: password
      EDGEX_SECURITY_SECRET_STORE: "false"
      Writable_Pipeline_Functions_HTTPPostJSON_Parameters_url: http://${DOCKER_HOST_IP}:7770
      Writable_LogLevel: DEBUG
    networks:
      edgex-network:
        aliases:
          - app-service-http-export

  app-service-mqtt-export:
    image: ${appService}
    ports:
      - "48097:48097"
    container_name: app-service-mqtt-export
    hostname: app-service-mqtt-export
    environment:
      edgex_profile: mqtt-export
      Service_Host: app-service-mqtt-export
      Clients_CoreData_Host: edgex-core-data
      Clients_Logging_Host: edgex-support-logging
      Registry_Host: edgex-core-consul
      Service_Port: 48097
      MessageBus_SubscribeHost_Host: edgex-core-data
      Database_Host: edgex-mongo
      Database_Username: appservice
      Database_Password: password
      EDGEX_SECURITY_SECRET_STORE: "false"
      Writable_Pipeline_Functions_MQTTSend_Addressable_Address: mqtt-broker
      Writable_LogLevel: DEBUG
    networks:
      edgex-network:
        aliases:
          - app-service-mqtt-export

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    hostname: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      edgex-network:
        aliases:
          - mqtt-broker

