  app-service-http-export:
    image: ${appService}
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48096:48096/tcp
    container_name: app-service-http-export
    hostname: app-service-http-export
    environment:
      EDGEX_PROFILE: http-export
      SERVICE_HOST: app-service-http-export
      CLIENTS_COREDATA_HOST: edgex-core-data
      REGISTRY_HOST: edgex-core-consul
      SERVICE_PORT: 48096
      MESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-core-data
      DATABASE_HOST: edgex-redis
      DATABASE_USERNAME: appservice
      DATABASE_PASSWORD: password
      EDGEX_SECURITY_SECRET_STORE: "false"
      WRITABLE_PIPELINE_FUNCTIONS_HTTPPOSTJSON_PARAMETERS_URL: http://${DOCKER_HOST_IP}:7770
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    networks:
      - edgex-network

  app-service-mqtt-export:
    image: ${appService}
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48097:48097/tcp
    container_name: app-service-mqtt-export
    hostname: app-service-mqtt-export
    environment:
      EDGEX_PROFILE: mqtt-export
      SERVICE_HOST: app-service-mqtt-export
      CLIENTS_COREDATA_HOST: edgex-core-data
      REGISTRY_HOST: edgex-core-consul
      SERVICE_PORT: 48097
      MESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-core-data
      DATABASE_HOST: edgex-mongo
      DATABASE_USERNAME: appservice
      DATABASE_PASSWORD: password
      EDGEX_SECURITY_SECRET_STORE: "false"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_BROKERADDRESS: tcp://mqtt-broker:1883
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_TOPIC: edgex-events
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    networks:
      - edgex-network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    hostname: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - edgex-network

  app-service-blackbox-tests:
    image: ${appService}
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48095:48095/tcp
    container_name: app-service-blackbox-tests
    hostname: app-service-blackbox-tests
    environment:
      EDGEX_PROFILE: blackbox-tests
      SERVICE_HOST: app-service-blackbox-tests
      CLIENTS_COREDATA_HOST: edgex-core-data
      REGISTRY_HOST: edgex-core-consul
      SERVICE_PORT: 48095
      EDGEX_SECURITY_SECRET_STORE: "false"
    depends_on:
      - consul
      - data
    networks:
      - edgex-network

  app-service-http-export-secrets:
    image: ${appService}
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48098:48098/tcp
    container_name: app-service-http-export-secrets
    hostname: app-service-http-export-secrets
    environment:
      EDGEX_PROFILE: http-export
      SERVICE_HOST: app-service-http-export-secrets
      CLIENTS_COREDATA_HOST: edgex-core-data
      REGISTRY_HOST: edgex-core-consul
      SERVICE_PORT: 48098
      DATABASE_HOSE: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_SERVERNAME: edgex-vault
      SECRETSTORE_PATH: /v1/secret/edgex/appservice-http-export-secrets/
      SECRETSTORE_TOKENFILE: /tmp/edgex/secrets/appservice-http-export-secrets/secrets-token.json
      WRITABLE_PIPELINE_FUNCTIONS_HTTPPOSTJSON_PARAMETERS_URL: http://${DOCKER_HOST_IP}:7770
      WRITABLE_LOGLEVEL: DEBUG
    volumes:
    - /tmp/edgex/secrets/edgex-application-service:/tmp/edgex/secrets/edgex-application-service:ro,z
    - /tmp/edgex/secrets/appservice-http-export-secrets:/tmp/edgex/secrets/appservice-http-export-secrets:ro,z
    depends_on:
      - consul
      - data
    networks:
      - edgex-network

  scalability-test-mqtt-export:
    image: ${appService}
    ports:
      - "48098:48098"
    container_name: scalability-test-mqtt-export
    hostname: scalability-test-mqtt-export
    environment:
      EDGEX_PROFILE: mqtt-export
      SERVICE_HOST: app-service-mqtt-export
      CLIENTS_COREDATA_HOST: edgex-core-data
      REGISTRY_HOST: edgex-core-consul
      SERVICE_PORT: 48098
      MESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-core-data
      DATABASE_HOST: edgex-redis
      DATABASE_USERNAME: appservice
      DATABASE_PASSWORD: password
      EDGEX_SECURITY_SECRET_STORE: "false"
      WRITABLE_PIPELINE_EXECUTIONORDER: "TransformToJSON, MQTTSecretSend"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_BROKERADDRESS: tcp://${MQTT_BROKER_IP}:1883
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_TOPIC: edgex-events
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    networks:
      - edgex-network
